# Generated by Django 3.2 on 2023-05-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frogs', '0002_alter_frogs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='frogs',
            table='frogs',
        ),
    ]
